# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

notifications:
  email:
    - melissa_johnson2@baylor.edu
    - gabriel.odom@med.maimi.edu
